-- Demo RAG corpus: a small curated set of BNS/BNSS/BSA statute chunks and a
-- cached set of (placeholder-but-structurally-real) Indian Kanoon judgments.
-- Embeddings are left NULL — retrieval falls back to keyword search until a real
-- embedder is wired (see app/pipeline/retrieval.py).
--
-- NOTE: statute text below is condensed/paraphrased for demo retrieval. Replace
-- with verbatim bare-act text from indiacode.nic.in before any real use.

INSERT INTO statute_chunks (code, section_no, heading, text, keywords) VALUES
('BNS', '303', 'Theft',
 'Whoever, intending to take dishonestly any movable property out of the possession of any person without that person''s consent, moves that property, is said to commit theft (s.303(1) definition). Punishment is provided in s.303(2): imprisonment which may extend to three years, or fine, or both.',
 'theft steal stole stolen took taking movable property motorcycle bike scooter vehicle phone mobile laptop cash jewellery valuables shop missing gone'),
('BNS', '304', 'Snatching',
 'Theft is snatching if, in order to commit theft, the offender suddenly or quickly or forcibly seizes, secures, grabs or takes away any movable property from any person or from his possession. Punishable with imprisonment up to three years and fine.',
 'snatching snatched grabbed pulled seized chain necklace bag purse mobile phone suddenly forcibly bike speeding'),
('BNS', '305', 'Theft in a dwelling house etc.',
 'Theft committed in any building, tent or vessel used as a human dwelling or for custody of property, or theft of means of transport, is punishable with imprisonment up to seven years and fine.',
 'theft dwelling house home residence building burglary stolen transport vehicle inside premises'),
('BNS', '308', 'Extortion',
 'Whoever intentionally puts any person in fear of injury and thereby dishonestly induces the person to deliver any property, valuable security or anything signed/sealed that may be converted into a valuable security, commits extortion. Base punishment under s.308(2): imprisonment up to seven years, or fine, or both; aggravated forms (fear of death/grievous hurt) carry higher punishment.',
 'extortion extort protection money demanded pay paid handed delivered fear threat threatened gang harm family monthly'),
('BNS', '309', 'Robbery',
 'Theft is robbery if, in order to commit theft, the offender voluntarily causes or attempts to cause death, hurt or wrongful restraint, or fear thereof. Extortion is robbery if committed in the presence of the person put in fear. Punishable with rigorous imprisonment up to ten years and fine.',
 'robbery robbed force pushed knocked shoved weapon hurt fear violence intercepted bike snatched gold chain'),
('BNS', '310', 'Dacoity',
 'When five or more persons conjointly commit or attempt to commit robbery, every person so committing or aiding commits dacoity. Punishable with rigorous imprisonment for life or up to ten years and fine.',
 'dacoity gang five persons group armed robbery looted'),
('BNS', '316', 'Criminal breach of trust',
 'Whoever, being in any manner entrusted with property or dominion over property, dishonestly misappropriates or converts it to his own use, or disposes of it in violation of any law/contract, commits criminal breach of trust (s.316(1)). General punishment under s.316(2): imprisonment up to five years, or fine, or both; aggravated forms apply to carriers, clerks/servants, public servants and bankers.',
 'criminal breach trust entrusted misappropriated misappropriation diverted embezzled embezzlement dishonestly converted clerk employee accountant cashier collections deposit depositing funds money company own personal account'),
('BNS', '318', 'Cheating',
 'Whoever by deceiving any person fraudulently or dishonestly induces the person to deliver any property, or to consent to retention of property, or intentionally induces an act/omission causing damage, commits cheating (s.318(1)). General punishment s.318(2); cheating and thereby dishonestly inducing delivery of property is punishable under s.318(4) with imprisonment up to seven years and fine.',
 'cheating cheated fraud fraudulent scam deceived deception induced dishonestly delivery property fake online upi otp phishing link bank official call advance payment duped debited transferred unknown account loan'),
('BNS', '319', 'Cheating by personation',
 'A person cheats by personation if he cheats by pretending to be some other person, or by knowingly substituting one person for another, or representing that he or any other person is a person other than he or such other person really is.',
 'personation impersonation impersonated posing pretending fake identity false name caller id claiming to be bank official'),
('BNS', '336', 'Forgery',
 'Whoever makes any false document or false electronic record, or part thereof, with intent to cause damage or injury, or to support any claim, or to commit fraud, commits forgery. Punishment varies by sub-section (e.g. s.336(2) harm to reputation; s.336(3) forgery of a document/electronic record).',
 'forgery forged fake counterfeit fabricated false document signature created'),
('BNS', '338', 'Forgery of valuable security, will, etc.',
 'Whoever forges a document which purports to be a valuable security or a will, or an authority to make/transfer a valuable security, or to receive money/property, is punishable with imprisonment for life or up to ten years and fine.',
 'forgery forged valuable security will bond cheque guarantee title deed bank fabricated'),
('BNS', '340', 'Forged document or electronic record used as genuine',
 'Whoever fraudulently or dishonestly uses as genuine any document or electronic record which he knows or has reason to believe to be forged is punishable as if he had himself forged it (s.340(2)).',
 'forged document used genuine fake submitted produced presented loan obtained'),
('BNS', '115', 'Voluntarily causing hurt',
 'Whoever voluntarily causes hurt is punishable with imprisonment up to one year, or fine which may extend to ten thousand rupees, or both.',
 'hurt injury injured beat beaten hit slapped punched wound pain minor bruises'),
('BNS', '117', 'Voluntarily causing grievous hurt',
 'Whoever voluntarily causes grievous hurt (as defined in s.116, including fracture or dislocation of a bone or tooth) is punishable with imprisonment up to seven years and fine.',
 'grievous hurt fracture fractured broken bone skull serious injury hospital hospitalization rod weapon iron medico-legal'),
('BNS', '131', 'Assault or criminal force otherwise than on grave provocation',
 'Whoever assaults or uses criminal force to any person otherwise than on grave and sudden provocation given by that person is punishable with imprisonment up to three months, or fine up to one thousand rupees, or both.',
 'assault criminal force attacked pushed struck hit shoved'),
('BNS', '351', 'Criminal intimidation',
 'Whoever threatens another with injury to person, reputation or property with intent to cause alarm commits criminal intimidation. Threat of death or grievous hurt is aggravated (s.351(2), up to seven years); anonymous threats are covered by s.351(3).',
 'intimidation threat threaten threatened kill harm burn message messages whatsapp call alarm withdraw complaint anonymous'),
('BNS', '330', 'House-trespass and house-breaking',
 'House-trespass is criminal trespass by entering or remaining in any building, tent or vessel used as a human dwelling or for worship or custody of property. House-breaking is house-trespass effected by specified means of entry.',
 'house trespass breaking broke entered intruder latch door window lock rear forced entry premises'),
('BNS', '331', 'Punishment for house-trespass or house-breaking',
 'Whoever commits house-trespass or house-breaking is punishable as specified; house-breaking by night (after sunset and before sunrise) attracts enhanced punishment with imprisonment and fine.',
 'house breaking night sunset sunrise burglary broke entered intruder latch door overnight'),
('BNSS', '173', 'Information in cognizable cases (FIR)',
 'Every information relating to the commission of a cognizable offence shall be reduced to writing and recorded; this constitutes the First Information Report (zero FIR and electronic registration provided for).',
 'fir first information report cognizable complaint registered reported lodged'),
('BNSS', '187', 'Police custody / remand',
 'Procedure where investigation cannot be completed in twenty-four hours; a Magistrate may authorise detention of the accused in custody (police or judicial) for the purposes of investigation, subject to the statutory 15-day/40-60-day limits.',
 'remand custody police judicial arrest arrested detention magistrate twenty-four hours interrogation'),
('BNSS', '105', 'Recording of search and seizure',
 'The process of conducting search or seizure shall be recorded through audio-video electronic means, preferably a mobile phone, and forwarded to the District Magistrate / Magistrate.',
 'search seizure seized recording audio video device electronic'),
('BNSS', '106', 'Power of police to seize property and seizure list',
 'A police officer may seize any property alleged or suspected to be stolen or found in circumstances creating suspicion of an offence; a list of seized items is prepared, signed by witnesses, and the seizure reported to the Magistrate.',
 'seize seized property stolen recovered seizure list witnesses memo panchnama'),
('BNSS', '193', 'Report on completion of investigation (charge-sheet / final report)',
 'On completion of investigation the officer in charge forwards to the Magistrate a report (final report / charge-sheet) in the form prescribed by the State Government, stating the parties, the offence/sections, the accused, and whether forwarded in custody. s.193(3) covers chain of custody of electronic devices; s.193(9) covers further/supplementary investigation.',
 'charge sheet chargesheet final report investigation completed accused filed magistrate'),
('BSA', '61', 'Electronic or digital record admissible',
 'Nothing in this Adhiniyam shall apply to deny the admissibility of an electronic or digital record in evidence merely on the ground that it is an electronic or digital record; such records have the same legal effect as paper records, subject to s.63.',
 'electronic digital record cctv footage video admissible evidence'),
('BSA', '62', 'Proof of contents of electronic records',
 'The contents of electronic records may be proved in accordance with the provisions of Section 63.',
 'electronic record proof contents prove'),
('BSA', '63', 'Admissibility of electronic records',
 'Electronic records are admissible as evidence subject to a certificate identifying the electronic record and describing the manner of its production. The certificate (in the form in the Schedule) must affirm the four conditions of s.63 and is in two parts — Part A (party producing the record) and Part B (expert).',
 'electronic digital record cctv footage video whatsapp message chat otp upi transaction logs call records bank statement certificate admissibility evidence')
ON CONFLICT DO NOTHING;

-- Cross-reference to the repealed codes (PS: "Cross-referenced IPC/CrPC/Evidence
-- Act provisions where needed"). Indicative equivalents for officer familiarity
-- and old case-law lookup — NOT the charging section (that is always the new code).
-- ⚠️ HUMAN-VERIFY exact old-code numbers before the live demo.
UPDATE statute_chunks SET old_code_ref = m.ref FROM (VALUES
  ('BNS','303','IPC 378/379 (theft)'),
  ('BNS','304','New offence under BNS (nearest old: IPC 379 theft)'),
  ('BNS','305','IPC 380 (theft in dwelling)'),
  ('BNS','308','IPC 383/384 (extortion)'),
  ('BNS','309','IPC 390/392 (robbery)'),
  ('BNS','310','IPC 391/395 (dacoity)'),
  ('BNS','316','IPC 405/406 (criminal breach of trust)'),
  ('BNS','318','IPC 415/417/420 (cheating)'),
  ('BNS','319','IPC 416/419 (cheating by personation)'),
  ('BNS','336','IPC 463/465 (forgery)'),
  ('BNS','338','IPC 467 (forgery of valuable security/will)'),
  ('BNS','340','IPC 471 (using forged document as genuine)'),
  ('BNS','115','IPC 321/323 (voluntarily causing hurt)'),
  ('BNS','117','IPC 322/325 (voluntarily causing grievous hurt)'),
  ('BNS','131','IPC 350/351/352 (assault or criminal force)'),
  ('BNS','351','IPC 503/506 (criminal intimidation)'),
  ('BNS','330','IPC 442/445 (house-trespass / house-breaking)'),
  ('BNS','331','IPC 451/453/456/457 (punishment for house-breaking)'),
  ('BNSS','173','CrPC 154 (FIR in cognizable cases)'),
  ('BNSS','187','CrPC 167 (custody/remand)'),
  ('BNSS','105','CrPC 100/165 (search & seizure)'),
  ('BNSS','106','CrPC 102 (police power to seize property)'),
  ('BNSS','193','CrPC 173 (final report / charge-sheet)'),
  ('BSA','61','Evidence Act s.65A (electronic records)'),
  ('BSA','62','Evidence Act s.65B (proof of electronic records)'),
  ('BSA','63','Evidence Act s.65B (admissibility + certificate)')
) AS m(code, section_no, ref)
WHERE statute_chunks.code = m.code AND statute_chunks.section_no = m.section_no;

-- ===========================================================================
-- DATASET EXPANSION (P1) — broader BNS/BNSS/BSA coverage so the classifier can
-- map a wider range of incident narratives. Same condensed/paraphrased style;
-- replace with verbatim bare-act text from indiacode.nic.in before real use.
-- ===========================================================================
INSERT INTO statute_chunks (code, section_no, heading, text, keywords) VALUES
-- --- offences against the human body --------------------------------------
('BNS', '101', 'Murder',
 'Culpable homicide is murder if the act by which death is caused is done with the intention of causing death, or with intention/knowledge as specified. Punishable with death or imprisonment for life, and fine.',
 'murder killed death intentionally stabbed shot strangled fatal deceased homicide deliberate premeditated weapon blood'),
('BNS', '103', 'Punishment for murder',
 'Whoever commits murder shall be punished with death or imprisonment for life and shall also be liable to fine; murder by a group of five or more on specified grounds (race, caste, sex, language) is covered by s.103(2).',
 'murder punishment death life imprisonment killed mob lynching group beaten to death'),
('BNS', '105', 'Punishment for culpable homicide not amounting to murder',
 'Whoever commits culpable homicide not amounting to murder is punishable with imprisonment for life, or up to ten years, and fine, where the act is done with intention; or up to ten years/fine where done with knowledge.',
 'culpable homicide not murder death sudden fight provocation without premeditation died injuries succumbed'),
('BNS', '109', 'Attempt to murder',
 'Whoever does any act with such intention or knowledge and under such circumstances that, if death were caused, the act would be murder, is guilty of attempt to murder. Punishable with imprisonment up to ten years and fine; life imprisonment if hurt is caused.',
 'attempt to murder tried to kill shot at stabbed fired attacked survived grievous injury jaan se maarne'),
('BNS', '137', 'Kidnapping',
 'Kidnapping is either from India or from lawful guardianship. Whoever takes or entices a minor (under 18 if female, under 18 if male per the section) or a person of unsound mind out of lawful guardianship without consent commits kidnapping. Punishable with imprisonment up to seven years and fine.',
 'kidnapping kidnapped abducted took away enticed minor child missing girl boy guardian without consent forcibly taken'),
('BNS', '140', 'Kidnapping or abduction for specified purposes (murder, ransom, etc.)',
 'Whoever kidnaps or abducts any person in order to murder, for ransom, to subject to grievous hurt/slavery, etc., is punishable with rigorous imprisonment up to ten years / life, and fine, as per the relevant sub-section.',
 'abduction ransom kidnapped for money demand extort hostage held captive confined beg slavery'),
('BNS', '64', 'Punishment for rape',
 'Whoever commits rape (as defined in s.63) shall be punished with rigorous imprisonment of not less than ten years, extendable to life, and fine; aggravated forms (by police officer, public servant, gang, on a minor) attract enhanced punishment.',
 'rape sexual assault forced intercourse without consent victim woman survivor molested raped aggravated'),
('BNS', '74', 'Assault or use of criminal force to woman with intent to outrage modesty',
 'Whoever assaults or uses criminal force to any woman intending to outrage, or knowing it likely to outrage, her modesty is punishable with imprisonment of one to five years and fine.',
 'outrage modesty molestation molested woman inappropriately touched groped criminal force assault eve teasing harassment'),
('BNS', '79', 'Word, gesture or act intended to insult modesty of a woman',
 'Whoever, intending to insult the modesty of a woman, utters any word, makes any sound/gesture, or exhibits any object intending it to be seen/heard by her, or intrudes upon her privacy, is punishable with simple imprisonment up to three years and fine.',
 'insult modesty woman obscene gesture word stalking privacy vulgar comment passed lewd'),
('BNS', '85', 'Husband or relative of husband subjecting a woman to cruelty',
 'Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty (harassment to coerce an unlawful dowry demand, or conduct driving her to suicide/grave injury) is punishable with imprisonment up to three years and fine.',
 'cruelty husband in-laws dowry harassment domestic violence beaten wife matrimonial demand taunted physical mental torture married woman sasural'),
('BNS', '80', 'Dowry death',
 'Where the death of a woman is caused by burns/bodily injury or occurs otherwise than under normal circumstances within seven years of marriage, and she was subjected to cruelty/harassment for dowry soon before death, it is dowry death. Punishable with imprisonment of not less than seven years up to life.',
 'dowry death bride burning married woman died seven years harassment cruelty unnatural death in-laws demand'),
('BNS', '69', 'Sexual intercourse by employing deceitful means',
 'Whoever, by deceitful means or by making a promise to marry without intention of fulfilling it, has sexual intercourse with a woman (not amounting to rape), is punishable with imprisonment up to ten years and fine.',
 'false promise marriage cheated sexual relationship deceit refused to marry breach promise woman'),
-- --- against property / cyber / public tranquillity ------------------------
('BNS', '324', 'Mischief',
 'Whoever with intent to cause, or knowing he is likely to cause, wrongful loss or damage to the public or any person, causes destruction of any property or any change diminishing its value/utility, commits mischief. Punishment graded by value/type of damage (e.g. s.324(2)-(5)).',
 'mischief damage damaged destroyed broke vandalism property loss vehicle smashed set fire crops public property'),
('BNS', '326', 'Mischief by fire or explosive (incl. damaging property)',
 'Mischief by fire or any explosive substance intending to cause, or knowing it likely to cause, damage is punishable with enhanced imprisonment depending on the property destroyed.',
 'arson fire burnt set ablaze explosive damaged building house shop vehicle torched'),
('BNS', '189', 'Unlawful assembly',
 'An assembly of five or more persons is unlawful if its common object is to commit an offence, resist law, criminal trespass, etc. Members are punishable; being armed with a deadly weapon is aggravated.',
 'unlawful assembly mob group five persons gathered crowd common object armed weapons sticks stones'),
('BNS', '191', 'Rioting',
 'Whenever force or violence is used by an unlawful assembly or any member in prosecution of the common object, every member is guilty of rioting. Punishable with imprisonment up to two years; rioting with a deadly weapon up to five years.',
 'rioting riot violence mob force stones pelting clash group fight weapons crowd damage'),
('BNS', '61', 'Criminal conspiracy',
 'When two or more persons agree to do, or cause to be done, an illegal act or a legal act by illegal means, such agreement is a criminal conspiracy. Punishable as for abetment / per the gravity of the offence conspired.',
 'conspiracy conspired agreement planned together plotted hatched plan group accused colluded'),
('BNS', '3', 'General explanations — common intention',
 'Where a criminal act is done by several persons in furtherance of the common intention of all, each is liable as if done by him alone (joint liability). Read with the specific charging section.',
 'common intention jointly together acted in furtherance several persons shared all accused'),
('BNS', '111', 'Organised crime',
 'Any continuing unlawful activity by a crime syndicate (e.g. kidnapping, extortion, contract killing, cyber-crime, trafficking) carried on as a member or on behalf of a syndicate is organised crime, punishable with severe imprisonment up to life and fine.',
 'organised crime syndicate gang racket continuing extortion contract killing cyber trafficking mafia network'),
('BNS', '112', 'Petty organised crime',
 'Petty organised crime (e.g. theft by gangs, snatching, pickpocketing, organised betting/cheating) by a group or gang causing general feeling of insecurity is punishable with imprisonment of one to seven years and fine.',
 'petty organised crime gang pickpocket snatching organised theft betting public insecurity group'),
('BNS', '152', 'Act endangering sovereignty, unity and integrity of India',
 'Whoever excites or attempts to excite secession, armed rebellion, subversive activities, or encourages feelings of separatist activities endangering the sovereignty, unity and integrity of India is punishable with imprisonment for life or up to seven years and fine.',
 'sedition sovereignty unity integrity secession rebellion subversive separatist anti-national'),
-- --- BNSS procedural ------------------------------------------------------
('BNSS', '35', 'When police may arrest without warrant',
 'A police officer may arrest without a warrant a person who commits a cognizable offence in his presence or against whom a reasonable complaint/credible information exists, subject to the safeguards (notice of appearance for offences punishable up to seven years).',
 'arrest without warrant cognizable offence police powers notice appearance safeguard reasonable'),
('BNSS', '37', 'Designated police officer / control room and arrest records',
 'The State shall designate a police officer in every district and police station to maintain information about arrested persons, and details of arrests shall be prominently displayed.',
 'arrest record control room designated officer details of arrested displayed information'),
('BNSS', '58', 'Person arrested to be produced before Magistrate within 24 hours',
 'No police officer shall detain an arrested person in custody for more than twenty-four hours (excluding journey time) without the special order of a Magistrate under s.187.',
 'twenty-four hours produced magistrate arrest custody detention limit'),
('BNSS', '176', 'Procedure for investigation',
 'An officer in charge of a police station may, on information of a cognizable offence, investigate the facts and circumstances; for offences punishable for seven years or more, forensic evidence must be collected and videographed at the scene.',
 'investigation procedure cognizable forensic crime scene videography evidence collected seven years'),
('BNSS', '183', 'Recording of confessions and statements by Magistrate',
 'A Magistrate may record any confession or statement made in the course of investigation; confessions must be recorded with due safeguards (voluntariness, warning).',
 'confession statement recorded magistrate 164 voluntary witness accused safeguard'),
('BNSS', '184', 'Medical examination of victim of rape',
 'Where rape/attempt is alleged, the victim shall be examined by a registered medical practitioner with consent, and the report forwarded; examination to be completed without delay.',
 'medical examination rape victim consent registered practitioner report mlc forensic'),
('BNSS', '230', 'Supply of copy of police report and documents to accused',
 'The Magistrate shall furnish to the accused, free of cost, a copy of the police report (charge-sheet), FIR, statements and documents relied upon, within fourteen days.',
 'copy chargesheet supplied accused fir statements documents fourteen days'),
-- --- BSA evidence ---------------------------------------------------------
('BSA', '2', 'Definitions — document and evidence include electronic',
 'Evidence includes statements and documents (including electronic and digital records) produced for inspection of the Court; the definitions extend documentary evidence to electronic records.',
 'evidence document definition electronic digital record statement court'),
('BSA', '57', 'Primary evidence',
 'Primary evidence means the document itself produced for inspection; where a document is created/stored electronically, each file is primary evidence.',
 'primary evidence original document electronic file inspection'),
('BSA', '58', 'Secondary evidence',
 'Secondary evidence includes certified copies, copies made by mechanical processes, and oral accounts of contents; admissible in specified circumstances.',
 'secondary evidence certified copy duplicate photocopy admissible'),
('BSA', '39', 'Opinion of experts',
 'When the Court has to form an opinion on a point of foreign law, science, art, handwriting, finger impressions or electronic/digital evidence, the opinions of persons specially skilled (experts) are relevant.',
 'expert opinion forensic handwriting fingerprint dna electronic digital examiner science relevant'),
('BSA', '160', 'Number of witnesses',
 'No particular number of witnesses is required for the proof of any fact; the Court may act on the testimony of a single reliable witness.',
 'number witnesses single witness sole testimony reliable proof'),
('BNS', '226', 'Attempt to commit suicide to compel/restrain public servant',
 'Whoever attempts to commit suicide with the intent to compel or restrain any public servant from discharging official duty is punishable with simple imprisonment up to one year, fine, community service, or all.',
 'attempt suicide compel public servant protest self harm threat'),
-- --- offences by/relating to public servants (corruption-adjacent) --------
('BNS', '198', 'Public servant disobeying law, with intent to cause injury',
 'Whoever, being a public servant, knowingly disobeys any direction of the law as to the way he is to conduct himself as such public servant, intending to cause, or knowing it likely that he will by such disobedience cause, injury to any person, is punishable with imprisonment up to one year, or fine, or both. Covers misuse of official position to harm a person.',
 'public servant official government officer abuse misuse of office position disobeyed law illegal demand harassment by official corruption bribe gratification withheld documents pending file'),
('BNS', '201', 'Public servant framing an incorrect document/record',
 'Whoever, being a public servant and charged with the preparation or translation of any document or electronic record, frames, prepares or translates it in a manner he knows or believes to be incorrect, intending or knowing it likely to cause injury, is punishable with imprisonment up to three years, or fine, or both.',
 'public servant official fabricated incorrect record document register entry tampered manipulated file false official record forged government'),
('BNS', '202', 'Public servant unlawfully engaging in trade or bidding for property',
 'Whoever, being a public servant, unlawfully engages in trade, or unlawfully buys or bids for certain property, contrary to the duties of his office, is punishable with imprisonment up to one year, or fine, or community service, or all.',
 'public servant official unlawful trade conflict of interest abuse office benefit personal gain corruption')
ON CONFLICT DO NOTHING;

-- Enrich extortion keywords so a bribe/illegal-gratification demand (withholding
-- an official act to induce payment) surfaces s.308 rather than the FIR section.
UPDATE statute_chunks
   SET keywords = keywords || ' bribe bribery illegal gratification corruption public servant official demanded money to release withhold rishvat lanch'
 WHERE code = 'BNS' AND section_no = '308';

-- Cross-refs for the public-servant offences (incl. special-law pointer).
UPDATE statute_chunks SET old_code_ref = m.ref FROM (VALUES
  ('BNS','198','IPC 166 (public servant disobeying law) · cf. Prevention of Corruption Act, 1988 s.7 for bribery'),
  ('BNS','201','IPC 167 (public servant framing incorrect record)'),
  ('BNS','202','IPC 168 (public servant unlawfully engaging in trade)')
) AS m(code, section_no, ref)
WHERE statute_chunks.code = m.code AND statute_chunks.section_no = m.section_no;

-- Cross-reference (old IPC/CrPC/IEA) for the expanded set. ⚠️ HUMAN-VERIFY.
UPDATE statute_chunks SET old_code_ref = m.ref FROM (VALUES
  ('BNS','101','IPC 300 (murder definition)'),
  ('BNS','103','IPC 302 (punishment for murder)'),
  ('BNS','105','IPC 304 (culpable homicide not amounting to murder)'),
  ('BNS','109','IPC 307 (attempt to murder)'),
  ('BNS','137','IPC 359/361/363 (kidnapping)'),
  ('BNS','140','IPC 364/364A/365 (abduction/ransom)'),
  ('BNS','64','IPC 376 (punishment for rape)'),
  ('BNS','74','IPC 354 (outraging modesty)'),
  ('BNS','79','IPC 509 (insulting modesty of a woman)'),
  ('BNS','85','IPC 498A (cruelty by husband/relatives)'),
  ('BNS','80','IPC 304B (dowry death)'),
  ('BNS','69','New offence under BNS (deceitful sexual intercourse)'),
  ('BNS','324','IPC 425/426 (mischief)'),
  ('BNS','326','IPC 435/436 (mischief by fire)'),
  ('BNS','189','IPC 141/142/144 (unlawful assembly)'),
  ('BNS','191','IPC 146/147/148 (rioting)'),
  ('BNS','61','IPC 120A/120B (criminal conspiracy)'),
  ('BNS','3','IPC 34 (common intention)'),
  ('BNS','111','New offence under BNS (organised crime; cf. MCOCA/UAPA frameworks)'),
  ('BNS','112','New offence under BNS (petty organised crime)'),
  ('BNS','152','New offence under BNS (cf. repealed IPC 124A sedition)'),
  ('BNS','226','IPC 309 (attempt to suicide context)'),
  ('BNSS','35','CrPC 41 (arrest without warrant)'),
  ('BNSS','37','CrPC 41C (control room / arrest records)'),
  ('BNSS','58','CrPC 57 (24-hour production)'),
  ('BNSS','176','CrPC 157 (procedure for investigation)'),
  ('BNSS','183','CrPC 164 (confessions/statements)'),
  ('BNSS','184','CrPC 164A (medical exam of rape victim)'),
  ('BNSS','230','CrPC 207 (supply of documents to accused)'),
  ('BSA','2','Evidence Act s.3 (definitions)'),
  ('BSA','57','Evidence Act s.62 (primary evidence)'),
  ('BSA','58','Evidence Act s.63/65 (secondary evidence)'),
  ('BSA','39','Evidence Act s.45/45A (expert opinion)'),
  ('BSA','160','Evidence Act s.134 (number of witnesses)')
) AS m(code, section_no, ref)
WHERE statute_chunks.code = m.code AND statute_chunks.section_no = m.section_no;

INSERT INTO judgments_cache (indiankanoon_doc_id, title, summary, tags) VALUES
('IK-1000001', 'State of Gujarat v. Accused (theft of property)',
 'Conviction for theft from a dwelling; discusses dishonest intention and possession.',
 ARRAY['theft','dwelling','intention']),
('IK-1000002', 'State v. Accused (cheating and inducement)',
 'Discusses essentials of cheating: deception and dishonest inducement to deliver property.',
 ARRAY['cheating','fraud','inducement']),
('IK-1000003', 'In re Electronic Evidence Certificate',
 'Lays down that electronic records require a valid certificate for admissibility.',
 ARRAY['electronic evidence','certificate','admissibility']),
('IK-1000004', 'Anvar P.V. v. P.K. Basheer (2014) 10 SCC 473',
 'Landmark: electronic records are admissible only with a s.65B Evidence Act certificate (now BSA s.63); secondary electronic evidence without the certificate is inadmissible.',
 ARRAY['electronic evidence','certificate','admissibility','65B','BSA 63']),
('IK-1000005', 'Arjun Panditrao Khotkar v. Kailash Kushanrao Gorantyal (2020) 7 SCC 1',
 'Clarifies that the s.65B certificate is a mandatory condition precedent to admissibility of electronic records; addresses when the certificate can be produced.',
 ARRAY['electronic evidence','certificate','admissibility','mandatory']),
('IK-1000006', 'Arnesh Kumar v. State of Bihar (2014) 8 SCC 273',
 'Guidelines restraining automatic arrest in offences punishable up to seven years (e.g. dowry cruelty); police must record reasons under arrest-checklist before arrest.',
 ARRAY['arrest','498A','cruelty','dowry','arrest guidelines','41 CrPC']),
('IK-1000007', 'Lalita Kumari v. Govt. of U.P. (2014) 2 SCC 1',
 'Registration of an FIR is mandatory if information discloses a cognizable offence; preliminary inquiry permissible only in limited categories.',
 ARRAY['FIR','cognizable','mandatory registration','154 CrPC']),
('IK-1000008', 'D.K. Basu v. State of West Bengal (1997) 1 SCC 416',
 'Lays down mandatory safeguards on arrest and detention (arrest memo, intimation to relatives, medical examination) to prevent custodial abuse.',
 ARRAY['arrest','custody','safeguards','arrest memo','remand']),
('IK-1000009', 'Selvi v. State of Karnataka (2010) 7 SCC 263',
 'Narco-analysis, polygraph and brain-mapping without consent violate Article 20(3); involuntary scientific tests are inadmissible.',
 ARRAY['confession','self-incrimination','scientific test','admissibility']),
('IK-1000010', 'Sharad Birdhichand Sarda v. State of Maharashtra (1984) 4 SCC 116',
 'The five golden principles (panchsheel) for conviction based on circumstantial evidence; the chain of circumstances must be complete.',
 ARRAY['circumstantial evidence','murder','chain of circumstances','proof']),
('IK-1000011', 'State of Maharashtra v. Accused (snatching/robbery)',
 'Distinguishes theft, snatching and robbery on the element of force/fear; recovery of property corroborates.',
 ARRAY['robbery','snatching','theft','force','recovery']),
('IK-1000012', 'State v. Accused (criminal breach of trust by employee)',
 'Entrustment plus dishonest misappropriation establishes criminal breach of trust; account books and audit relevant.',
 ARRAY['criminal breach of trust','entrustment','misappropriation','employee']),
('IK-1000013', 'Shafhi Mohammad v. State of H.P. (cyber/CCTV evidence)',
 'Discusses production of electronic evidence where the device is not in the party''s possession; later clarified by Arjun Panditrao.',
 ARRAY['electronic evidence','CCTV','certificate','possession']),
('IK-1000014', 'State v. Accused (dowry death — s.304B presumption)',
 'Death within seven years of marriage with proof of cruelty soon before death raises the statutory presumption of dowry death.',
 ARRAY['dowry death','304B','presumption','cruelty','married woman']),
('IK-1000015', 'State v. Accused (extortion — demand of money with threat)',
 'Demand of money or property coupled with putting the victim in fear of injury or wrongful loss satisfies the offence of extortion; delivery of property pursuant to the threat discussed.',
 ARRAY['extortion','threat','demand','money','property','bribe']),
('IK-1000016', 'State v. Public Servant (bribery / illegal gratification)',
 'Public servant demanding or accepting illegal gratification to perform or withhold an official act; corroboration, demand and recovery discussed under the Prevention of Corruption Act read with extortion principles.',
 ARRAY['bribery','corruption','public servant','illegal gratification','demand','PC Act','extortion'])
ON CONFLICT DO NOTHING;
