-- Demo RAG corpus: a small curated set of BNS/BNSS/BSA statute chunks and a
-- cached set of (placeholder-but-structurally-real) Indian Kanoon judgments.
-- Embeddings are left NULL — retrieval falls back to keyword search until a real
-- embedder is wired (see app/pipeline/retrieval.py).
--
-- NOTE: statute text below is condensed/paraphrased for demo retrieval. Replace
-- with verbatim bare-act text from indiacode.nic.in before any real use.

INSERT INTO statute_chunks (code, section_no, heading, text, keywords) VALUES
('BNS', '303', 'Theft',
 'Whoever, intending to take dishonestly any movable property out of the possession of any person without that person''s consent, moves that property, is said to commit theft (s.303(1) definition). Punishment is provided in s.303(2): imprisonment which may extend to three years, or fine, or both.',
 'theft steal stole stolen took taking movable property motorcycle bike scooter vehicle phone mobile laptop cash jewellery valuables shop missing gone'),
('BNS', '304', 'Snatching',
 'Theft is snatching if, in order to commit theft, the offender suddenly or quickly or forcibly seizes, secures, grabs or takes away any movable property from any person or from his possession. Punishable with imprisonment up to three years and fine.',
 'snatching snatched grabbed pulled seized chain necklace bag purse mobile phone suddenly forcibly bike speeding'),
('BNS', '305', 'Theft in a dwelling house etc.',
 'Theft committed in any building, tent or vessel used as a human dwelling or for custody of property, or theft of means of transport, is punishable with imprisonment up to seven years and fine.',
 'theft dwelling house home residence building burglary stolen transport vehicle inside premises'),
('BNS', '308', 'Extortion',
 'Whoever intentionally puts any person in fear of injury and thereby dishonestly induces the person to deliver any property, valuable security or anything signed/sealed that may be converted into a valuable security, commits extortion. Base punishment under s.308(2): imprisonment up to seven years, or fine, or both; aggravated forms (fear of death/grievous hurt) carry higher punishment.',
 'extortion extort protection money demanded pay paid handed delivered fear threat threatened gang harm family monthly'),
('BNS', '309', 'Robbery',
 'Theft is robbery if, in order to commit theft, the offender voluntarily causes or attempts to cause death, hurt or wrongful restraint, or fear thereof. Extortion is robbery if committed in the presence of the person put in fear. Punishable with rigorous imprisonment up to ten years and fine.',
 'robbery robbed force pushed knocked shoved weapon hurt fear violence intercepted bike snatched gold chain'),
('BNS', '310', 'Dacoity',
 'When five or more persons conjointly commit or attempt to commit robbery, every person so committing or aiding commits dacoity. Punishable with rigorous imprisonment for life or up to ten years and fine.',
 'dacoity gang five persons group armed robbery looted'),
('BNS', '316', 'Criminal breach of trust',
 'Whoever, being in any manner entrusted with property or dominion over property, dishonestly misappropriates or converts it to his own use, or disposes of it in violation of any law/contract, commits criminal breach of trust (s.316(1)). General punishment under s.316(2): imprisonment up to five years, or fine, or both; aggravated forms apply to carriers, clerks/servants, public servants and bankers.',
 'criminal breach trust entrusted misappropriated misappropriation diverted embezzled embezzlement dishonestly converted clerk employee accountant cashier collections deposit depositing funds money company own personal account'),
('BNS', '318', 'Cheating',
 'Whoever by deceiving any person fraudulently or dishonestly induces the person to deliver any property, or to consent to retention of property, or intentionally induces an act/omission causing damage, commits cheating (s.318(1)). General punishment s.318(2); cheating and thereby dishonestly inducing delivery of property is punishable under s.318(4) with imprisonment up to seven years and fine.',
 'cheating cheated fraud fraudulent scam deceived deception induced dishonestly delivery property fake online upi otp phishing link bank official call advance payment duped debited transferred unknown account loan'),
('BNS', '319', 'Cheating by personation',
 'A person cheats by personation if he cheats by pretending to be some other person, or by knowingly substituting one person for another, or representing that he or any other person is a person other than he or such other person really is.',
 'personation impersonation impersonated posing pretending fake identity false name caller id claiming to be bank official'),
('BNS', '336', 'Forgery',
 'Whoever makes any false document or false electronic record, or part thereof, with intent to cause damage or injury, or to support any claim, or to commit fraud, commits forgery. Punishment varies by sub-section (e.g. s.336(2) harm to reputation; s.336(3) forgery of a document/electronic record).',
 'forgery forged fake counterfeit fabricated false document signature created'),
('BNS', '338', 'Forgery of valuable security, will, etc.',
 'Whoever forges a document which purports to be a valuable security or a will, or an authority to make/transfer a valuable security, or to receive money/property, is punishable with imprisonment for life or up to ten years and fine.',
 'forgery forged valuable security will bond cheque guarantee title deed bank fabricated'),
('BNS', '340', 'Forged document or electronic record used as genuine',
 'Whoever fraudulently or dishonestly uses as genuine any document or electronic record which he knows or has reason to believe to be forged is punishable as if he had himself forged it (s.340(2)).',
 'forged document used genuine fake submitted produced presented loan obtained'),
('BNS', '115', 'Voluntarily causing hurt',
 'Whoever voluntarily causes hurt is punishable with imprisonment up to one year, or fine which may extend to ten thousand rupees, or both.',
 'hurt injury injured beat beaten hit slapped punched wound pain minor bruises'),
('BNS', '117', 'Voluntarily causing grievous hurt',
 'Whoever voluntarily causes grievous hurt (as defined in s.116, including fracture or dislocation of a bone or tooth) is punishable with imprisonment up to seven years and fine.',
 'grievous hurt fracture fractured broken bone skull serious injury hospital hospitalization rod weapon iron medico-legal'),
('BNS', '131', 'Assault or criminal force otherwise than on grave provocation',
 'Whoever assaults or uses criminal force to any person otherwise than on grave and sudden provocation given by that person is punishable with imprisonment up to three months, or fine up to one thousand rupees, or both.',
 'assault criminal force attacked pushed struck hit shoved'),
('BNS', '351', 'Criminal intimidation',
 'Whoever threatens another with injury to person, reputation or property with intent to cause alarm commits criminal intimidation. Threat of death or grievous hurt is aggravated (s.351(2), up to seven years); anonymous threats are covered by s.351(3).',
 'intimidation threat threaten threatened kill harm burn message messages whatsapp call alarm withdraw complaint anonymous'),
('BNS', '330', 'House-trespass and house-breaking',
 'House-trespass is criminal trespass by entering or remaining in any building, tent or vessel used as a human dwelling or for worship or custody of property. House-breaking is house-trespass effected by specified means of entry.',
 'house trespass breaking broke entered intruder latch door window lock rear forced entry premises'),
('BNS', '331', 'Punishment for house-trespass or house-breaking',
 'Whoever commits house-trespass or house-breaking is punishable as specified; house-breaking by night (after sunset and before sunrise) attracts enhanced punishment with imprisonment and fine.',
 'house breaking night sunset sunrise burglary broke entered intruder latch door overnight'),
('BNSS', '173', 'Information in cognizable cases (FIR)',
 'Every information relating to the commission of a cognizable offence shall be reduced to writing and recorded; this constitutes the First Information Report (zero FIR and electronic registration provided for).',
 'fir first information report cognizable complaint registered reported lodged'),
('BNSS', '187', 'Police custody / remand',
 'Procedure where investigation cannot be completed in twenty-four hours; a Magistrate may authorise detention of the accused in custody (police or judicial) for the purposes of investigation, subject to the statutory 15-day/40-60-day limits.',
 'remand custody police judicial arrest arrested detention magistrate twenty-four hours interrogation'),
('BNSS', '105', 'Recording of search and seizure',
 'The process of conducting search or seizure shall be recorded through audio-video electronic means, preferably a mobile phone, and forwarded to the District Magistrate / Magistrate.',
 'search seizure seized recording audio video device electronic'),
('BNSS', '106', 'Power of police to seize property and seizure list',
 'A police officer may seize any property alleged or suspected to be stolen or found in circumstances creating suspicion of an offence; a list of seized items is prepared, signed by witnesses, and the seizure reported to the Magistrate.',
 'seize seized property stolen recovered seizure list witnesses memo panchnama'),
('BNSS', '193', 'Report on completion of investigation (charge-sheet / final report)',
 'On completion of investigation the officer in charge forwards to the Magistrate a report (final report / charge-sheet) in the form prescribed by the State Government, stating the parties, the offence/sections, the accused, and whether forwarded in custody. s.193(3) covers chain of custody of electronic devices; s.193(9) covers further/supplementary investigation.',
 'charge sheet chargesheet final report investigation completed accused filed magistrate'),
('BSA', '61', 'Electronic or digital record admissible',
 'Nothing in this Adhiniyam shall apply to deny the admissibility of an electronic or digital record in evidence merely on the ground that it is an electronic or digital record; such records have the same legal effect as paper records, subject to s.63.',
 'electronic digital record cctv footage video admissible evidence'),
('BSA', '62', 'Proof of contents of electronic records',
 'The contents of electronic records may be proved in accordance with the provisions of Section 63.',
 'electronic record proof contents prove'),
('BSA', '63', 'Admissibility of electronic records',
 'Electronic records are admissible as evidence subject to a certificate identifying the electronic record and describing the manner of its production. The certificate (in the form in the Schedule) must affirm the four conditions of s.63 and is in two parts — Part A (party producing the record) and Part B (expert).',
 'electronic digital record cctv footage video whatsapp message chat otp upi transaction logs call records bank statement certificate admissibility evidence')
ON CONFLICT DO NOTHING;

-- Cross-reference to the repealed codes (PS: "Cross-referenced IPC/CrPC/Evidence
-- Act provisions where needed"). Indicative equivalents for officer familiarity
-- and old case-law lookup — NOT the charging section (that is always the new code).
-- ⚠️ HUMAN-VERIFY exact old-code numbers before the live demo.
UPDATE statute_chunks SET old_code_ref = m.ref FROM (VALUES
  ('BNS','303','IPC 378/379 (theft)'),
  ('BNS','304','New offence under BNS (nearest old: IPC 379 theft)'),
  ('BNS','305','IPC 380 (theft in dwelling)'),
  ('BNS','308','IPC 383/384 (extortion)'),
  ('BNS','309','IPC 390/392 (robbery)'),
  ('BNS','310','IPC 391/395 (dacoity)'),
  ('BNS','316','IPC 405/406 (criminal breach of trust)'),
  ('BNS','318','IPC 415/417/420 (cheating)'),
  ('BNS','319','IPC 416/419 (cheating by personation)'),
  ('BNS','336','IPC 463/465 (forgery)'),
  ('BNS','338','IPC 467 (forgery of valuable security/will)'),
  ('BNS','340','IPC 471 (using forged document as genuine)'),
  ('BNS','115','IPC 321/323 (voluntarily causing hurt)'),
  ('BNS','117','IPC 322/325 (voluntarily causing grievous hurt)'),
  ('BNS','131','IPC 350/351/352 (assault or criminal force)'),
  ('BNS','351','IPC 503/506 (criminal intimidation)'),
  ('BNS','330','IPC 442/445 (house-trespass / house-breaking)'),
  ('BNS','331','IPC 451/453/456/457 (punishment for house-breaking)'),
  ('BNSS','173','CrPC 154 (FIR in cognizable cases)'),
  ('BNSS','187','CrPC 167 (custody/remand)'),
  ('BNSS','105','CrPC 100/165 (search & seizure)'),
  ('BNSS','106','CrPC 102 (police power to seize property)'),
  ('BNSS','193','CrPC 173 (final report / charge-sheet)'),
  ('BSA','61','Evidence Act s.65A (electronic records)'),
  ('BSA','62','Evidence Act s.65B (proof of electronic records)'),
  ('BSA','63','Evidence Act s.65B (admissibility + certificate)')
) AS m(code, section_no, ref)
WHERE statute_chunks.code = m.code AND statute_chunks.section_no = m.section_no;

INSERT INTO judgments_cache (indiankanoon_doc_id, title, summary, tags) VALUES
('IK-1000001', 'State of Gujarat v. Accused (theft of property)',
 'Conviction for theft from a dwelling; discusses dishonest intention and possession.',
 ARRAY['theft','dwelling','intention']),
('IK-1000002', 'State v. Accused (cheating and inducement)',
 'Discusses essentials of cheating: deception and dishonest inducement to deliver property.',
 ARRAY['cheating','fraud','inducement']),
('IK-1000003', 'In re Electronic Evidence Certificate',
 'Lays down that electronic records require a valid certificate for admissibility.',
 ARRAY['electronic evidence','certificate','admissibility'])
ON CONFLICT DO NOTHING;
